### PR TITLE
Ported to 1.15.2

### PR DESCRIPTION
**Pull request by GirafiStudios**
A slightly wonky port of Neat to 1.15.2. Partially inspired by the Fabric port of Neat called "Orderly".

Generally stuff is working correctly, but the corner icons is flickering a bit.

### CODE REVIEW

**Comment by Kamefrede** [comment]
neat

**Comment by FizzBuzz3000** [comment]
is

**Comment by Techno-Turnovers** [comment]
a

**Comment by qybust** [comment]
Looking forward to the 1.15 version coming soon

**Pull request merged**
