### PR TITLE
Added missing blend disabling. Closes #4

### LINKED ISSUE #4: Interference with Botania 1.8 wisp particles
This is more aimed at @61352151511 since they ported it to 1.8.x:

If a Neat unit frame and any Botania wisp particle is on screen at the same time, the wisp particle loses all of its alpha transparency. 
I'm not sure whose fault it is, Neat for not cleaning GL state or Botania 1.8 not setting it correctly, so opening an issue on both. See https://github.com/williewillus/Botania/issues/38

### PR DESCRIPTION
**Pull request by GirafiStudios**

### CODE REVIEW

**Comment by Vazkii** [comment]
What does this accomplish?

**Comment by GirafiStudios** [comment]
It fixes the issue in https://github.com/Vazkii/Neat/issues/4.

When enabling blend and not disabling it again, it's very likely that it will cause issues in other mods.

Screenshot: http://prntscr.com/9sjyq0

**Comment by Vazkii** [comment]
Can you confirm it does actually fix the issue? It seems highly unlikely.

**Comment by GirafiStudios** [comment]
Yes it does, I have tested it under the same conditions as my screenshot from my previous comment & it fixes it :)

**Comment by Vazkii** [comment]
Ok then.

**Pull request merged**
